### ISSUE TITLE
C example is not working

### ISSUE THREAD

**Issue by Silur** [radare/radare2-r2pipe#11]
the ![c example](https://github.com/radare/radare2-r2pipe/tree/master/c) compiled with `gcc -o test test.c -I /usr/include/libr -lr_socket -lr_util` probably blocks the main thread because the only output is `[+] r2pipe child is <PID>` and hangs forever without any result from r2cmd.

example: https://asciinema.org/a/1tq7b85zhzrxgpmt2qhcyrcbt
My system is x86_64 Arch 4.8.13
radare2 1.1.0 9999999 @ linux-x86-64 git.1.1.0
commit: HEAD build: 2016-12-20

**Comment by radare** [comment]
fixed in master... but we should run this testsuite in travis

**Comment by radare** [comment]
@Maijin ^
