### ISSUE TITLE
r2pipe python __init__.py relative import would not work in python3

### ISSUE THREAD

**Issue by Frefreak** [radare/radare2-r2pipe#20]
https://github.com/radare/radare2-r2pipe/blob/master/python/r2pipe/__init__.py#L40-L44
```python
try:
	import native
	has_native = True
except:
	has_native = False
```
Since python3 forbidden relative import `has_native` would always be **False** in py3. How about change it to something like `from native import RCore` and modify https://github.com/radare/radare2-r2pipe/blob/master/python/r2pipe/__init__.py#L206. It seems currently RCore is the only attribute used from native.

**Comment by radare** [comment]
Please send a pr

**Comment by radare** [comment]
Or just click the pencil button in github, it will do the fork, branch, pr in just 2 clicks
