### ISSUE TITLE
Disabling warnings from r2pipe

### ISSUE THREAD

**Issue by invictus-0x90** [radare/radare2-r2pipe#26]
Hi, we are processing a large number of binaries using r2pipe (python), and have been trying to find a way to disable warnings. Mainly, whenever we open the pipe we get:
Warning: cannot initialize dynamic strings

As you can imagine, when this occurs over 100+ times it can get quite frustrating. I've so far tried editing r2's __init__.py and setting stderr=PIPE to stop it being printed to the terminal, but as that didn't work im assuming this output is to stdout.

Any ideas?

**Comment by radare** [comment]
Close stderr fd

**Comment by invictus-0x90** [comment]
in my code or yours? doing sys.stderr.close() in my code doesn't work

**Comment by radare** [comment]
use r2 -2, so.. add “-2” in the list of arguments. this will make r2 close the stderr fd for you

**Comment by invictus-0x90** [comment]
Yep that worked a charm, thanks for that!
