### ISSUE TITLE
R2Pipe Python Fails Sometimes

### ISSUE THREAD

**Issue by Stormys** [radare/radare2-r2pipe#28]
So, I can't seem to figure out why and what is causing r2pipe to fail for me.
I am writing a program to essential go a list of binaries, get the functions, and select certain functions that I have marked as of interest and run ```ag [func]``` to obtain their dot graph. 

Yet, I have not been able to figure out why my code will return NoneType object errors with ```ag [func]``` on all of the functions except main when I simple comment out ```handle.cmd('aaa')``` and uncomment the other one command. Yet, the current implementation below works 100% of the time. Why and how would a previous command impact other commands?  
```
def openBinary(file):
    handle = r2pipe.open(file)
    handle.cmd('aaa')
    #handle.cmd('e anal.jmptbl=true;e anal.jmpref=true;e anal.jmpabove=true;aaa')
    return handle
```

I am also positive that the only command in my code that appears to fail is ```ag [func]```. Other commands such as ```af``` had to be commented out as well as they seemed to impact both my ```aflj``` and ```ag``` command.

**Comment by radare** [comment]
cant reproduce on mac with /bin/ls

can you provide more details, like version of r2, which binary are you using, which OS, version of python, version of the r2pipe module, etc ?

**Comment by Stormys** [comment]
Here is a full python script that causes my issue along with a compiled version of cat and the output of running my script on cat.

Let me know if you are able to reproduce it

[r2pipe_issue_28.tar.gz](https://github.com/radare/radare2-r2pipe/files/1242291/r2pipe_issue_28.tar.gz)

**Comment by Stormys** [comment]
So I figured out my issue. It is occurring due to radare2 asking "Do you want to print x lines?" after a command. Is there a way to disable this? If not I believe this would be useful to implement especially for those using r2pipe to interact with radare.

**Comment by lzina** [comment]
Hi @Stormys ,
Did you find any way to disable "Do you want to print x lines?" message?

Thanks,

**Comment by radare** [comment]
e scr.interactive=0

But in r2pipe mode this shouldnt be needed

**Comment by Carl1981** [comment]
`help **where do we go from here** `
