### ISSUE TITLE
r2pipe output from one command does not correspond to json equivalent.

### ISSUE THREAD

**Issue by invictus-0x90** [radare/radare2-r2pipe#31]
This isn't making much sense to me, but if I analyse a function such as the snippet here using pdf:
<...snip....>
0x004210aa      0f8454ffffff   je 0x421004
0x004210b0      4981fa001000.  cmp r10, 0x1000
0x004210b7      0f8447ffffff   je 0x421004
0x004210bd      31c0           xor eax, eax
0x004210bf      e9fefeffff     jmp 0x420fc2

the end of the json output (pdfj) doesn't seem to be correct. I'm mainly trying to extract the byte code, and I end up with:
{"offset":4329642,"esil":"zf,?{,4329476,rip,=,}","refptr":false,"fcn_addr":4329120,"fcn_last":4329662,"size":6,"opcode":"je 0x421004","bytes":"0f8454ffffff","family":"cpu","type":"cjmp","type_num":2147483649,"type2_num":0,"jump":4329476,"fail":4329648},{"offset":4329648,"size":1,"type":"invalid"}, {"offset":4329649,"size":1,"type":"invalid"},{"offset":4329650,"esil":"$0,if,=","refptr":false,"fcn_addr":4329120,"fcn_last":4329667,"size":1,"opcode":"cli","bytes":"fa","family":"priv","type":"mov","type_num":9,"type2_num":0},{"offset":4329651,"size":1,"type":"invalid"}]

You can see that after the je instruction, all it sees are a load of invalid 1 byte operations.

**Comment by radare** [comment]
This issue is not related to r2pipe. Please fill this in r2 and provide version of r2, way to reproduce, binary sample, etc
