### ISSUE TITLE
Python3 module fails after 1 command

### ISSUE THREAD

**Issue by indivisible** [radare/radare2-r2pipe#37]
Hi, the latest r2pipe module fails with python3.6 on the 2nd command with `r2pipe.cmdj.Error: I/O operation on closed file`

The cause of the error seems to be the `TextIOWrapper` being created on every call in https://github.com/radare/radare2-r2pipe/blob/55b275a91287e26a60b367db5d7c3edc8bead416/python/r2pipe/__init__.py#L169

This fixes it for me:

    diff --git a/python/r2pipe/__init__.py b/python/r2pipe/__init__.py
    index 99be568..8eff472 100644
    --- a/python/r2pipe/__init__.py
    +++ b/python/r2pipe/__init__.py
    @@ -166,7 +166,10 @@ class open:
                     if sys.version_info >= (3, 0):
                             self.process.stdin.write(bytes(cmd + '\n', 'utf-8'))
                             # XXX: Use the TextIOWrapper or we can get stuck in an endless loop!
    -                        r = TextIOWrapper(self.process.stdout, encoding='utf8')
    +                        r = getattr(self, '_process_stdout_wrapper', None)
    +                        if r is None:
    +                                r = TextIOWrapper(self.process.stdout, encoding='utf8')
    +                                self._process_stdout_wrapper = r
                     else:
                             self.process.stdin.write(cmd + '\n')
                             r = self.process.stdout

**Comment by Maijin** [comment]
Use Pull-Request, diff are useless
