### ISSUE TITLE
No output from r2pipe since latest updates

### ISSUE THREAD

**Issue by securisec** [radare/radare2-r2pipe#45]
```
radare2 2.2.0-git 16829 @ darwin-x86-64 git.2.1.0-188-g032aff2d5
commit: 032aff2d556a70dfcc391d111f5aaeda2423c70a build: 2017-12-21__22:58:03
```
`r2pipe==0.9.6`

Since the latest updates, I cant get any output from the python r2pipe. I have tested this on multiple systems and the issue seems to persist. Second machine had r2pipe version 0.9.4 installed.

**Comment by radare** [comment]
ive pushed 0.9.7, pls let me know if that works for you, but it was fine for me, at least the test scripts was passing

**Comment by securisec** [comment]
@radare I dont think the problem is with r2pipe. The problem started since the last couple of builds of r2. I tested the latest version for r2 with r2pipe python versions 0.9.4-0.9.7 and its the same issue. See the reproducing steps:

```
┌─[/tmp][]
└─▪ r2 -v
radare2 2.2.0-git 16778 @ linux-x86-64 git.2.1.0-194-g84e3786
commit: 84e37862489ec17a49d648fe1f2f852ba28ead32 build: 2017-12-22__14:22:06
┌─[/tmp][]
└─▪ pip freeze | grep r2pipe
r2pipe==0.9.7
┌─[/tmp][]
└─▪ cat r.py
import r2pipe
r = r2pipe.open('/bin/ls')
print r.cmd('ij')
┌─[/tmp][]
└─▪ python r.py 
Usage #!interpreter [<args>] [<file] [<<eof] 
|  #                     comment - do nothing
|  #!                    list all available interpreters
|  #!python              run python commandline
|  #!python foo.py       run foo.py python script (same as '. foo.py')
|  #!python arg0 a1 <<q  set arg0 and arg1 and read until 'q'
```

**Comment by securisec** [comment]
What is quirky is that `r.cmdj('ij')` works, but using r.cmd('aa') before running anything else will show v so that whole script crashes.  
```
Usage #!interpreter [<args>] [<file] [<<eof] 
|  #                     comment - do nothing
|  #!                    list all available interpreters
```

**Comment by securisec** [comment]
Another example:
```
import r2pipe

r = r2pipe.open('/tmp/bin-linux/crackme0x00')
r.cmd('aa')
print r.cmdj('afl')
```
output:
```
None
r2pipe.cmdj.Error: No JSON object could be decoded
```

**Comment by securisec** [comment]
https://pastebin.com/8MafHTwT

**Comment by securisec** [comment]
This was happening due to incorrectly commenting out a line in .radare2rc. Dont use `#foo`. It is `# foo`
