### ISSUE TITLE
r2pipe Python returns empty string

### ISSUE THREAD

**Issue by Wenzel** [radare/radare2-r2pipe#74]
Hi,

I have a case here where I use `r2pipe` to script a debugger plugin for `radare2`
https://github.com/Wenzel/r2vmi/blob/master/examples/watch_syscall.py

What my script is doing:
~~~Python
r2 = r2pipe.open(r2_url, ["-d", "-2"])
r2.cmd('db {}'.format(hex(syscall_addr)))
r2.cmd('dc')
registers = r2.cmdj('drj')
...
~~~

The problem i'm facing, is that sometimes the `drj` command fails because the JSON returned is invalid.

By investigating a bit the problem, i spawned an `IPython` shell right after `r2.cmd('db {}'.format(hex(syscall_addr)))`, and i observed this behavior:

![empty_string](https://user-images.githubusercontent.com/964610/45950593-256ded80-c009-11e8-8b5b-f23d2b6c1099.png)

So sometimes r2pipe is not getting the right command output.

Any ideas ?
Thanks.

**Comment by Wenzel** [comment]
It may be related to #54.

**Comment by radare** [comment]
still?

**Comment by Wenzel** [comment]
@radare I'm not working on this anymore, so I can't tell if the is still there.
You can close the issue if you want.
