### ISSUE TITLE
Modify section permissions with python

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [radare/radare2-r2pipe#78]
Hi to all,
with some change in the radare2 behavior I can't use the "S" command to modify the section permission.
I need to make executable all the sections of a binary file in order to find all the functions, by default radare2 does not scan not executable section
Thus I want to ask how I can achieve this task in python with the r2pipe api

**Comment by radare** [comment]
e anal.in=io.maps
E anal.noncode=true

No need to modify any section

**Comment by radare** [comment]
thats unrealted to r2pipe
