### ISSUE TITLE
Failed to retrieve cmd/cmdj results on python r2pipe 1.0.0

### ISSUE THREAD

**Issue by HongxuChen** [radare/radare2-r2pipe#83]
When using r2pipe 1.0.0, it has issues to retrieve cmdj/cmd results. Here are some of the tries.
![2018-12-01-004214_1130x736_scrot](https://user-images.githubusercontent.com/843267/49302385-f6409480-f501-11e8-928d-43edb6fafeaa.png)
The behavior is quite different from previous one such as 0.9.9 where we can use cmdj/cmd to get the output directly.

**Comment by HongxuChen** [comment]
`/bin/zgrep` is not a good example since it's a script. but binaries such as `/bin/tempfile` also have this issue.

**Comment by radare** [comment]
Can you write a test as a pullreq? Because iirc i tried all the tests in the r2pipe repo before publishing the new version. I am not maintaining this code but some ppl was asking me to push this release because they said it was fixing many things.. but seems like its the other way :D

**Comment by a1ext** [comment]
@HongxuChen could you test on 1.1.0 version?

**Comment by HongxuChen** [comment]
@a1ext It works now!
