### ISSUE TITLE
Rap not adding text comments as expected

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-r2pipe#96]
From @bannsec 

I'm attempting to use rap protocol to add comments to a remote r2 server. The setup is:

- r2 ./binary
- =&:12345

Then in a second window (in python):
```python
r2 = r2pipe.open("rap://127.0.0.1:12345")
r2.cmd('T test')
```

Oddly enough, when I do a `r2.cmd('T')` in the python window, it shows the text. But when i just do `T` in the r2 window, it does not show the text.

I'd like to be able to send text/other remote commands to the r2 server that update that r2 instance.

https://github.com/radare/radare2/issues/10378

**Comment by radare** [comment]
still? we probably want to have an r2pipe testsuite... would u like to help on that?

**Comment by radare** [comment]
because that works fine for me

```
$ python
Python 2.7.10 (default, Feb 22 2019, 21:55:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import r2pipe
>>> r2 = r2pipe.open("rap://127.0.0.1:12345")
Connected to: 127.0.0.1 at port 12345
>>> r2.cmd('T test')
u''
>>> r2.cmd('?E Hello')
u" .--.     .-------.\n |   \\    |       |\n | O o   <  Hello |\n |   | /  |       |\n |  ( /   `-------'\n |   / \n `--'\n"
>>> r2.cmd('T')
u'1 test\n'
>>>
```
