### ISSUE TITLE
r2pipe python (dc) problem

### ISSUE THREAD

**Issue by fennecfox0x01** [radare/radare2-r2pipe#97]
Hello, I'm trying to use r2pipe python, but it seems not working (Release` r2pipe.py 1.2.0`).

File: _test_r2pipe.py_
```
import r2pipe

r = r2pipe.open("./test")
r.cmd('doo')
r.cmd('aa')
r.cmd('db main')
r.cmd('dc')
r.cmd('dr')
r.cmd('dc')
```
Simple file to test _test.c_

```
#include <stdio.h>

void main(){
    printf("hello\n");
}

```
So I run the python script
```
$ python3 test.py 
Process with PID 4956 started...
File dbg:///home/invictus1306/Documents/temp_r2_issue/test  reopened in read-write mode
= attach 4956 4956
```
No output, and with a different program that require user inputs, there is no possibility to add it.

The same problem is present also in the last version of r2.

**Comment by radare** [comment]
Why not use -d instead of ood?

**Comment by fennecfox0x01** [comment]
I already try with
`r = r2pipe.open("./test", flags=['-d'])
`
but nothing change, same problem

**Comment by Ricx8** [comment]
@fennecfox0x01 can you print something between each command to see where is actually failing, also which OS are you working on?. I'm having the same problem but I think is not `dc` exactly. I Think is the `ood` command in the first place (That it should work, but it doesn't) I actually took the time to compile and try your code and the `ood` does not work. Now, the reason you don't see anything with the `-d` option is because you are never printing the registers. Try this, I'm pretty sure it is going to work for you as well:

```
#!/usr/bin/python
import r2pipe

r = r2pipe.open('test', ['-d'])
r.cmd('aa')
r.cmd('db main')
r.cmd('dc')
reg = r.cmd('dr')
print(reg)
r.cmd('dc')
```

@radare This is a problem because in order to give parameter from python we can do it easily with `doo` but `doo` doesn't work. I also try the three methods from here ["User input via stdin"](https://r2wiki.readthedocs.io/en/latest/home/radare2-python-scripting/) and Method1 doesn't work with the latest r2 (at least in macOS), Method3 we have to change the values manually in the profile. I guess Method2 works but is not very ideal since we have to write the profile in python... I'm pretty sure is `doo` the one with the bug.

**Comment by Ricx8** [comment]
It most be a macOS issue. I texted in Linux and works. I tested in three different macs and I have that problem.
Tested on:
macOS 10.12 (16A323)    - Darwin 16.0.0  NOT WORKING
OS X 10.11.4 (15E65)       - Darwin 15.4.0  NOT WORKING
macOS 10.14.4 (18E226) - Darwin 18.5.0  NOT WORKING
Linux 4.15.0-47-generic   WORKING

I didn't tested on Windows.

**Comment by a1ext** [comment]
on windows it works well:
![image](https://user-images.githubusercontent.com/14978853/56797192-d5fcd380-681c-11e9-850d-83b7edbc75d2.png)

**Comment by Ricx8** [comment]
> on windows it works well:
> ![image](https://user-images.githubusercontent.com/14978853/56797192-d5fcd380-681c-11e9-850d-83b7edbc75d2.png)

The code that you grab was my, that one should work. The command with the problem is `doo` can you try the code that @fennecfox0x01 wrote?.

**Comment by a1ext** [comment]
![image](https://user-images.githubusercontent.com/14978853/56798131-e01fd180-681e-11e9-9985-fda15c265fb5.png)

**Comment by Ricx8** [comment]
Thanks. That will help somebody. So there is a big chance that this problem is affecting only MacOS. I don't know what OS is @fennecfox0x01 using but I'm pretty sure by now that he is using MacOS.

**Comment by a1ext** [comment]
> Thanks. That will help somebody. So there is a big chance that this problem is affecting only MacOS. I don't know what OS is @fennecfox0x01 using but I'm pretty sure by now that he is using MacOS.

I think on MacOS the user folder usually looks different, like `/Uses/username`

**Comment by a1ext** [comment]
@fennecfox0x01 Could you provide more information about your environment?

**Comment by fennecfox0x01** [comment]
Hello @Ricx8 @a1ext thanks for your comments.
I'm using Ubuntu as system.

Please try to see if this other program works for you:

```
#include<stdio.h>

int menu(){
    int choice;
    do {
        printf("Menu\n\n");
        printf("Add\n");
        printf("Search\n");
        printf("Exit\n");
        scanf("%d", &choice);

        switch (choice) {
            case 1:
                printf("add\n");
                break;
            case 2:
                printf("Search\n");
                break;
            case 3:
                printf("Exit\n");
                break;
            default:
                printf("Try again\n");
                break;
        }
    } while(choice !=3);

    return 0;
}
int main() {
    menu();
    return 0;
}
```
This is my script:
```
import r2pipe

r = r2pipe.open("./test2", flags=['-d'])
r.cmd('aa')
r.cmd('db main')
r.cmd('dc')
print r.cmd('dr')
r.cmd('dc')
```
This is the result:
```
$ python test.py 
Process with PID 8411 started...
= attach 8411 8411
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
rax = 0x00400708
rbx = 0x00000000
rcx = 0x00000000
rdx = 0x7ffdb283c9a8
r8 = 0x00400790
r9 = 0x7f8891d99ab0
r10 = 0x00000846
r11 = 0x7f88919df740
r12 = 0x00400550
r13 = 0x7ffdb283c990
r14 = 0x00000000
r15 = 0x00000000
rsi = 0x7ffdb283c998
rdi = 0x00000001
rsp = 0x7ffdb283c8b8
rbp = 0x00400720
rip = 0x00400708
rflags = 0x00000246
orax = 0xffffffffffffffff

```
It never end, and there is not output.

**Comment by Ricx8** [comment]
That is not a radare2 problem. That is your code that it is in an infinite loop. You never give a value to 'choice' 
Please check your program first with radare2 and then try with r2pipe. I'm confident that this bug is real but is affecting MacOS I have tested in 5 different mac  and 2 different Linux, and seams to work on Linux

**Comment by fennecfox0x01** [comment]
@Ricx8 thanks for your answer. With radare2 it works well, and with the old veresion of r2pipe it was working fine.

This is how it works with radare2

```
 r2 -d test2
Process with PID 3283 started...
= attach 3283 3283
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
 -- Please register your copy of r2 today! Only £29.90!
[0x7f6feee56c30]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x7f6feee56c30]> db main
[0x7f6feee56c30]> dc
hit breakpoint at: 400708
[0x00400708]> dr
rax = 0x00400708
rbx = 0x00000000
rcx = 0x00000000
rdx = 0x7ffcf741ea08
r8 = 0x00400790
r9 = 0x7f6feee66ab0
r10 = 0x00000846
r11 = 0x7f6feeaac740
r12 = 0x00400550
r13 = 0x7ffcf741e9f0
r14 = 0x00000000
r15 = 0x00000000
rsi = 0x7ffcf741e9f8
rdi = 0x00000001
rsp = 0x7ffcf741e918
rbp = 0x00400720
rip = 0x00400708
rflags = 0x00000246
orax = 0xffffffffffffffff
[0x00400708]> dc
Menu

Add
Search
Exit
1
add
Menu

Add
Search
Exit
3
Exit
[0x7f6feeb58748]>
```
With r2pipe, I don't have the possibility to choose an option and the menu is not printed.

**Comment by Ricx8** [comment]
@fennecfox0x01 it's that the same code? because the code that you posted before is not even working by itself.

**Comment by fennecfox0x01** [comment]
@Ricx8 yes it is the same code, but it is just an example, if you try with any program that require user input (at running time) it will not works with r2pipe. After the "dc" command you cannot see output and you cannot type inputs.

**Comment by Ricx8** [comment]
@fennecfox0x01 I understand now what you are exactly talking about. Let's start with something simple and follow the next steps so we all can agree.

- [ ] Compile this hello world:
```
#include <stdio.h>
int main(){
   printf("Hello, World!");
   return 0;
}
```

- [ ]  Write the script:
```
#!/usr/bin/python
import r2pipe

r = r2pipe.open('hello', ['-d'])
r.cmd('db main')
r.cmd('dc')
reg = r.cmd('dr rax')
r.cmd('dc')
```

- [ ] You should get a similar output:
```
Process with PID 11742 started...
= attach 11742 11742
bin.baddr 0x564f6c805000
Using 0x564f6c805000
asm.bits 64
hit breakpoint at: 564f6c80564a
```

Yes! there is not "Hello, World!" anywhere because you never printed....

- [ ]  Write the modifications in the script:
```
#!/usr/bin/python
import r2pipe

r = r2pipe.open('hello', ['-d'])
r.cmd('db main')
r.cmd('dc')
reg = r.cmd('dr rax')
print("rax: "+reg)
print(r.cmd('dc'))
r.cmd('dc')
```
And you should get an output similar to this:
```
Process with PID 12123 started...
= attach 12123 12123
bin.baddr 0x55854b37c000
Using 0x55854b37c000
asm.bits 64
hit breakpoint at: 55854b37c64a
rax: 0x55854b37c64a

Hello, World!
child exited with status 0

==> Process finished
```

That should solve your problem. Is not a bug. I guess we can add a verbose mode.

**Comment by a1ext** [comment]
I think he wants to see the output of his application in python, but r2pipe doesn't transfer stdout/stderr to the user, there is no such capability. But you will see the output in a console, from which you start that script

**Comment by Ricx8** [comment]
@a1ext i think all he needs to do is print `dc` that way he actually is printing the `out.decode('utf8')` from 'open_sync - _cmd_process'

**Comment by fennecfox0x01** [comment]
@Ricx8 @a1ext thanks for your comments. So from my understanding, when we run the "dc" command, it is not possible to have the control of stdout/stderr/stdin (of the process under debug).

Then it is not a bug.

Thanks!

**Comment by Ricx8** [comment]
@fennecfox0x01 you can printed `print(r.cmd('dc'))`

**Comment by fennecfox0x01** [comment]
yes I already try it, and it is fine for stdout, thank you :) but not for stdin
